### ISSUE TITLE
Pie chart is not visible on my report

### ISSUE THREAD

**Issue by deepalirc** [uttesh/pdfngreport#10]
Hi,

I have added the pdfreport.pie.chart.type=normal and pdfreport.chart=show in my pdfng properties file but still i cannot see the pie chart can someone please tell me what is missing.I also added all the necessary jar files.Please help me resolve this issue.

Thanks in advance.

**Comment by uttesh** [comment]
@deepalirc  Is sample code is working fine? , are you getting any error ? no need to set "pdfreport.chart" to show.

eclipse sample code : https://github.com/uttesh/pdfngreport/raw/gh-pages/download/eclipse_archieve/pdfngreport_sample.zip

**Comment by deepalirc** [comment]
Thanks for the response.

Yes I have run the sample code it works fine but for my project it is 
not displayed.
Also if the test name is big then it overlays on the case column Can we 
modify it to wrap the text in test.

Thanks,
Deepali

On 10/7/2015 11:40 PM, uttesh wrote:

> @deepalirc https://github.com/deepalirc Is sample code is working 
> fine? , are you getting any error ? no need to set "pdfreport.chart" 
> to show.
> 
> eclipse sample code : 
> https://github.com/uttesh/pdfngreport/raw/gh-pages/download/eclipse_archieve/pdfngreport_sample.zip
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/uttesh/pdfngreport/issues/10#issuecomment-146281459.

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

**Comment by deepalirc** [comment]
Missed some question,

I have a feeling that some of the jar is missing in my project.But 
cannot find which.

Thanks,
Deepali

-------- Forwarded Message --------
Subject:    Re: [pdfngreport] Pie chart is not visible on my report (#10)
Date:   Thu, 8 Oct 2015 09:14:24 +0530
From:   Deepali Mahajan dmahajan@bizmaticsinc.com
To:     uttesh/pdfngreport 
reply@reply.github.com 

Thanks for the response.

Yes I have run the sample code it works fine but for my project it is 
not displayed.
Also if the test name is big then it overlays on the case column Can we 
modify it to wrap the text in test.

Thanks,
Deepali

On 10/7/2015 11:40 PM, uttesh wrote:

> @deepalirc https://github.com/deepalirc Is sample code is working 
> fine? , are you getting any error ? no need to set "pdfreport.chart" 
> to show.
> 
> eclipse sample code : 
> https://github.com/uttesh/pdfngreport/raw/gh-pages/download/eclipse_archieve/pdfngreport_sample.zip
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/uttesh/pdfngreport/issues/10#issuecomment-146281459.

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

**Comment by uttesh** [comment]
@deepalirc  copy all jars from sample code ext-lib to your project and try .
your project using ant or maven? 
maven will get all dependency jars from repository.

if your method name is big than it will take that as name, single word cannot be wrapped. its always better to keep short method names next version i will make library to use testng @test name attribute instead of method name.

ext-lib :

avalon-framework-api-4.2.0.jar
avalon-framework-api-4.3.1.jar
avalon-framework-impl-4.2.0.jar
avalon-framework-impl-4.3.1.jar
batik-anim-1.8.jar
batik-awt-util-1.8.jar
batik-bridge-1.8.jar
batik-css-1.8.jar
batik-dom-1.8.jar  
batik-ext-1.8.jar
batik-extension-1.8.jar
batik-gvt-1.8.jar
batik-parser-1.8.jar
batik-script-1.8.jar
batik-svg-dom-1.8.jar
batik-svggen-1.8.jar
batik-transcoder-1.8.jar
batik-util-1.8.jar
batik-xml-1.8.jar
bsh-2.0b4.jar
commons-io-1.3.1.jar
commons-logging-1.0.4.jar
fop-2.0.jar
hamcrest-core-1.1.jar
jcommander-1.27.jar
jcommon-1.0.16.jar
jfreechart-1.0.13.jar
junit-4.10.jar
pdfngreport-2.0.9.jar
snakeyaml-1.6.jar
testng-6.8.jar
xalan-2.7.0.jar
xml-apis-1.3.04.jar
xml-apis-ext-1.3.04.jar
xmlgraphics-commons-2.0.1.jar

Thanks

**Comment by deepalirc** [comment]
I added all the jar files in my project but still getting the same see 
attached report.If you see the spacing between the columns is not 
correct so at the end there is space but it is not used and my test name 
is overlapped.
Is there any solution to this.Please help.

Thanks,
Deepali

On 10/8/2015 9:35 AM, uttesh wrote:

> @deepalirc https://github.com/deepalirc copy all jars from sample to 
> your project and try . your project using ant or maven?
> maven will get all dependency jars from repository.
> 
> if your method name is big than it will take that as name, single word 
> cannot be wrapped. its always better to keep short method names next 
> version i will make library to use testng @test 
> https://github.com/test name attribute instead of method name.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/uttesh/pdfngreport/issues/10#issuecomment-146414190.

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

**Comment by deepalirc** [comment]
My project is a maven project.

On 10/8/2015 9:35 AM, uttesh wrote:

> @deepalirc https://github.com/deepalirc copy all jars from sample to 
> your project and try . your project using ant or maven?
> maven will get all dependency jars from repository.
> 
> if your method name is big than it will take that as name, single word 
> cannot be wrapped. its always better to keep short method names next 
> version i will make library to use testng @test 
> https://github.com/test name attribute instead of method name.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/uttesh/pdfngreport/issues/10#issuecomment-146414190.

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

**Comment by deepalirc** [comment]
No documents attached so adding screen shots

On 10/8/2015 9:35 AM, uttesh wrote:

> @deepalirc https://github.com/deepalirc copy all jars from sample to 
> your project and try . your project using ant or maven?
> maven will get all dependency jars from repository.
> 
> if your method name is big than it will take that as name, single word 
> cannot be wrapped. its always better to keep short method names next 
> version i will make library to use testng @test 
> https://github.com/test name attribute instead of method name.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/uttesh/pdfngreport/issues/10#issuecomment-146414190.

## 

Thanks & Regards,
Deepali Mahajan
Automation Manager
Bizmatics Inc.
Web :www.bizmaticsinc.com
Email:dmahajan@bizmaticsinc.com

**Comment by uttesh** [comment]
maven it will take all dependency jar that should not be the problem i guess, can send me pdfngreport.properties file, pom.xml just pdfngreport related snippet.

**Comment by deepalirc** [comment]
Attached is the pom.xml and pdfng properties file.Please confirm after 
you receive the file.

Thanks,
Deepali

#pdfreport.title=PDF NG Report Title loading properties
#pdfreport.chart=show
#pdfreport.logger=true

#Title
pdfreport.title.text=Automation Patch Testing Report
pdfreport.title.align=left

# application build version

pdfreport.app.build.version=Build V3B2 Patch 193

# Build System Details manual/code/hide code is default, use hide for not to display

# enable below only for manual setting by setting code mode it will automactically populate the values in report

# manual only for the mobile/tab env related details

#pdfreport.build.system.details.by=code
#pdfreport.additional.line1=OS : testOS (64 bit)
#pdfreport.additional.line2=SYSTEM : test@testingbox
#pdfreport.additional.line3=Lorem ipsum dolor sit amet

#TimeColumn Date Format
#"yyyy.MM.dd G 'at' HH:mm:ss z" | 2001.07.04 AD at 12:08:56 PDT
#"EEE, MMM d, ''yy" | Wed, Jul 4, '01
#"h:mm a"  |  12:08 PM
#"hh 'o''clock' a, zzzz" | 12 o'clock PM, Pacific Daylight Time
#"K:mm a, z" | 0:08 PM, PDT
#"yyyyy.MMMMM.dd GGG hh:mm aaa" | 02001.July.04 AD 12:08 PM
#"EEE, d MMM yyyy HH:mm:ss Z"  |  Wed, 4 Jul 2001 12:08:56 -0700
#"yyMMddHHmmssZ" | 010704120856-0700
#"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" |  2001-07-04T12:08:56.235-0700
#"yyyy-MM-dd'T'HH:mm:ss.SSSXXX" |  2001-07-04T12:08:56.235-07:00
#"YYYY-'W'ww-u" | 2001-W27-3

pdfngreport.time.column.format=MMMM dd YYYY hh:MM:sss

#Logo
#pdfreport.logo=show
#pdfreport.report.logo.file=E:/rivetsys/automation/pdfnglogo/logo.png
#pdfreport.report.logo.align=right

# chat related

pdfreport.pie.chart.type=normal
#pdfreport.pie.chart.type=explode

# pdf report output location

pdfreport.outputdir=TestResults/pdfngreport

# tables/page setting : show/hide

pdfreport.exception.page=show

# Below setting only for selenium user for selenium failed screen shot link show related

#pdfreport.show.selenium.screenshot.link=show
#pdfreport.selenium.failed.test.screenshot.outputdir=E:/rivetsys/automation/loan_connector_10Sep14Nova/loan_connector/screenshots

# Custom color setting Coming soon on 3.0.0 version

**Comment by uttesh** [comment]
@deepalirc missing pom.xml snippet? sample report?. send to my email
