### ISSUE TITLE
Failed Test cases status coming in Skipped and Skipped coming in failed

### ISSUE THREAD

**Issue by smitjain87** [uttesh/pdfngreport#2]
Hi
I used your code for PDF generation. PDF is generating properly. Only issue is on front page above pie chart, Failed test case count is populating in skipped and skipped test case count coming in failed.

Please check this issue. I am unable to solve it.

Please help.

Thanks & Regards
Smit Jain
9663310652
email: smitjain87@hotmail.com

**Comment by uttesh** [comment]
Thanks smit,

 Fixed the reported issue in release 2.0.4. released 2.0.4 version

https://oss.sonatype.org/content/repositories/releases/com/uttesh/pdfngreport/2.0.4/pdfngreport-2.0.4.jar 

updated both eclipse and other samples with latest release jar

Thanks,
Uttesh
