### ISSUE TITLE
Pie chart is not visible on my report

### ISSUE THREAD

**Issue by karthikeyanameex** [uttesh/pdfngreport#20]
Hi uttesh,

I have added the pdfreport.pie.chart.type=explode in my pdfng properties file but still i cannot see the pie chart can someone please tell me what is missing.I also added all maven dependencies in POM.xml.Please help me resolve this issue.

Thank you.

**Comment by uttesh** [comment]
@karthikeyanameex  could please provide me more details, is the sample code is working fine? or send me your pdfngreport.properties and testng.xml  and error messages ....which will help me to debug the issue your facing.

Thanks

**Comment by karthikeyanameex** [comment]
Hi uttesh,

I run sample code, but I am not able to see chart in that sample report. Kindly find the below mentioned pdfngreport.properties and testng.xml of mine.

---pdfngreport.properties---

#Title
pdfreport.title.text=Sample Automated Test Report
pdfreport.title.align=left

#report file name
pdfreport.file.name=Sample_automated_pdf_report

# application build version

#pdfreport.app.build.version=Build v1.0

# Build System Details manual/code/hide code is default, use hide for not to display

# enable below only for manual setting by setting code mode it will automatically populate the values in report

# manual only for the mobile/tab env related details

# pdfreport.build.system.details.by=code

# set above manual and enable below properties

#pdfreport.additional.line1=OS : testOS (64 bit)
#pdfreport.additional.line2=SYSTEM : test@testingbox
#pdfreport.additional.line3=Lorem ipsum dolor sit amet

#TimeColumn Date Format
#"yyyy.MM.dd G 'at' HH:mm:ss z" | 2001.07.04 AD at 12:08:56 PDT
#"EEE, MMM d, ''yy" | Wed, Jul 4, '01
#"h:mm a"  |  12:08 PM
#"hh 'o''clock' a, zzzz" | 12 o'clock PM, Pacific Daylight Time
#"K:mm a, z" | 0:08 PM, PDT
#"yyyyy.MMMMM.dd GGG hh:mm aaa" | 02001.July.04 AD 12:08 PM
#"EEE, d MMM yyyy HH:mm:ss Z"  |  Wed, 4 Jul 2001 12:08:56 -0700
#"yyMMddHHmmssZ" | 010704120856-0700
#"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" |  2001-07-04T12:08:56.235-0700
#"yyyy-MM-dd'T'HH:mm:ss.SSSXXX" |  2001-07-04T12:08:56.235-07:00
#"YYYY-'W'ww-u" | 2001-W27-3

pdfngreport.time.column.format=MMMM dd YYYY hh:MM:sss

#Logo
pdfreport.logo=show
pdfreport.report.logo.file=C:/Karthikeyan/Automation Projects/Pilot Project/GA/pdfreport/ameexlogo.jpg
pdfreport.report.logo.align=right

# chat related

#pdfreport.pie.chart.type=normal
pdfreport.pie.chart.type=explode

# pdf report output location

pdfreport.outputdir=./pdfreport

# tables/page setting : show/hide

pdfreport.exception.page=show

# for the better view or use of the space please use only 4 column. showing all columns will make the view cluttered

pdfreport.table.column.time=show
pdfreport.table.column.test=show
pdfreport.table.column.case=show
pdfreport.table.column.timetaken=show
pdfreport.table.column.description=show

# Below setting only for selenium user for selenium failed screen shot link show related

pdfreport.show.selenium.screenshot.link=show
pdfreport.selenium.failed.test.screenshot.outputdir=./FailCaseScreenshot

# error screen shot/image name standards.

#image type : png
#image name : className + "_" + methodName

# Custom color setting Coming soon on 3.0.0 version

---testng.xml---

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
suite name="Suite"

parameter name="pdfngreport-properties" value="./pdfngreport.properties"

listeners  
    listener class-name="com.uttesh.pdfngreport.PDFReportListener"
  listeners
  test name="Test"
    classes
      class name="testcases.TC001"
    classes
  test 
suite

Kindly, help me on this problem. Thank you Uttesh.

**Comment by karthikeyanameex** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">

<parameter name="pdfngreport-properties" value="./pdfngreport.properties" />

<listeners>    
    <listener class-name="com.uttesh.pdfngreport.PDFReportListener" />
  </listeners>
  <test name="Test">
    <classes>
      <class name="testcases.TC001"/>
    </classes>
  </test> 
</suite>

**Comment by uttesh** [comment]
@karthikeyanameex provide the proper output location 

> pdfreport.outputdir=**./pdfreport**

send me the build console output...are u using ant or maven ?
send me the console out of the build.

Thanks,

**Comment by karthikeyanameex** [comment]
Report Location : ./pdfreportFile Name : Sample_automated_pdf_report.pdf
pdf report file path :C:\Karthikeyan\Automation Projects\Live Projects\GA.\pdfreport\Sample_automated_pdf_report.pdf

this is my console output

**Comment by karthikeyanameex** [comment]
Hi uttesh,

After giving full path now chart is appear. Thank you for your time and wonderful support. once again thank you, thank you so much

**Comment by uttesh** [comment]
@karthikeyanameex  thanks for using the library, Any queries and enhancement feel free add on git and add star if this library is useful to requirement.
