### ISSUE TITLE
Ant build.xml is giving issue

### ISSUE THREAD

**Issue by smitjain87** [uttesh/pdfngreport#3]
Hi I am running my Test Case through Ant build.xml

I am getting given issue:

 [testng] Error on line 70 of :
   [testng]   Cannot find a matching 2-argument function named {http://xml.apache.org/xslt/java}format()
   [testng] ; SystemID: ; Line#: 70; Column#: -1
   [testng] net.sf.saxon.trans.DynamicError: Cannot find a matching 2-argument function named {http://xml.apache.org/xslt/java}format()
   [testng]     at net.sf.saxon.expr.ErrorExpression.evaluateItem(ErrorExpression.java:53)
   [testng]     at net.sf.saxon.expr.ErrorExpression.iterate(ErrorExpression.java:66)
   [testng]     at net.sf.saxon.expr.Atomizer.iterate(Atomizer.java:99)
   [testng]     at net.sf.saxon.expr.FirstItemExpression.evaluateItem(FirstItemExpression.java:81)

Please find given my build.xml

<project name="Custom_Report" default="runTestNG" basedir=".">
    <taskdef name="testng" classname="org.testng.TestNGAntTask">
        <classpath>
            <pathelement location="ext-lib/testng-6.8.5.jar"/>
        </classpath>
    </taskdef>

```
<property name="test.dir" location="src" />
<property name="lib.dir" location="ext-lib" />
<property name="classes.dir" location="build" />



<path id="classpath.test">
    <fileset dir="${lib.dir}">
        <include name="**/*.jar"/>
    </fileset>
    <pathelement location="${classes.dir}" />
</path>

<!-- ==================== Clean Target ==================== -->
<target name="clean" description="Delete build and packaging directories">
    <delete includeEmptyDirs="true" failonerror="false">
        <fileset dir="${testng.output.dir}"/>
    </delete>

    <delete dir="${classes.dir}" />
</target>

<!-- ==================== Compile Target ==================== -->
<target name="compile-test" depends="clean">
    <mkdir dir="${classes.dir}"/>
    <javac srcdir="${test.dir}" destdir="${classes.dir}" verbose="false" includeantruntime="true">
        <classpath refid="classpath.test" />
    </javac>
</target>


<!-- ==================== runTestNG Target ==================== -->
<target name="runTestNG" depends="compile-test">
    <testng classpathref="classpath.test" useDefaultListeners="false"  haltonfailure="false">
        <xmlfileset dir="." includes="TestNG2.xml" />
    </testng>
</target>
```

</project>

Please help

I am defining pdfreport listeners in my TestNG.xml file

Thanks & Regards
Smit Jain
9663310652

**Comment by uttesh** [comment]
Hi Smit,

I just downloaded sample from the web and executed ant, its working fine.

Error on line 70?..ant xml is not having line 70, could you please validate once your not missing
anything.!!!

my testing log :

C:\Users\uttesh\Downloads\pdfngreportdemo-master
(1)\pdfngreportdemo-master>ant
Buildfile: C:\Users\uttesh\Downloads\pdfngreportdemo-master
(1)\pdfngreportdemo-master\build.xml

clean:

compile-test:
    [mkdir] Created dir: C:\Users\uttesh\Downloads\pdfngreportdemo-master
(1)\pdfngreportdemo-master\classes
    [javac] Compiling 4 source files to
C:\Users\uttesh\Downloads\pdfngreportdemo-master
(1)\pdfngreportdemo-master\classes

runTestNG:
   [testng] [TestNG] Running:
   [testng]   C:\Users\uttesh\Downloads\pdfngreportdemo-master
(1)\pdfngreportdemo-master\testng.xml
   [testng]
   [testng]
   [testng] ===============================================
   [testng] Simple Reporter Suite
   [testng] Total tests run: 15, Failures: 4, Skips: 7
   [testng] ===============================================
   [testng]
   [testng] pdf report file path
:E:\rivetsys\automation\pdfngreport\pdfng-report-22-Jun-2015-01-07-31-PM.pdf
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #1.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #2.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #3.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #4.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #5.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #6.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #7.
   [testng] Jun 22, 2015 1:07:33 PM
org.apache.fop.events.LoggingEventListener processEvent
   [testng] INFO: Rendered page #8.
   [testng] The tests failed.

BUILD SUCCESSFUL
Total time: 4 seconds

**Comment by uttesh** [comment]
I'm online on https://gitter.im/uttesh/pdfngreport, you can ping me for quick
support on any issues

**Comment by uttesh** [comment]
pdfngreport 2.0.5 RELEASED and new features are.
1. Add company/client/project logo image to pdf report.
2. swap/align title and log image files.
3. Added new pie chart with "Explode" mode.
4. Added new icon set on tables and action links.
5. Added selenium failed test screen shot link on failed test table.
6. updated supportive jar files to latest versions.

![adding_logo](https://cloud.githubusercontent.com/assets/2218611/8462865/35d91e36-2054-11e5-8118-2a147a8d134b.png)
![explode_chart](https://cloud.githubusercontent.com/assets/2218611/8462866/35ff7b8a-2054-11e5-8f1b-fa8c5b6bcf7a.png)
![icon1](https://cloud.githubusercontent.com/assets/2218611/8462871/3627270c-2054-11e5-9a4f-6de6bde82c93.png)
![icon2](https://cloud.githubusercontent.com/assets/2218611/8462867/3625a38c-2054-11e5-9e5e-8d0e692b7221.png)
![icon3](https://cloud.githubusercontent.com/assets/2218611/8462870/3626e544-2054-11e5-82ae-d2b857657dbb.png)
![icon4](https://cloud.githubusercontent.com/assets/2218611/8462869/3626703c-2054-11e5-9096-262f4bb1a4d9.png)
![title_logo_align](https://cloud.githubusercontent.com/assets/2218611/8462868/36262406-2054-11e5-92c0-1b2054f2b5b1.png)
