### ISSUE TITLE
Exception Summary Page Not Required

### ISSUE THREAD

**Issue by smitjain87** [uttesh/pdfngreport#6]
Hi Uttesh,

There is no issue in your code. Your PDF reporting code is very use full for me.

I have a request. Is it possible that in the PDF report the Exception summary page will not come.

In Exception summary your PDF report is giving correct result, but for us is we need to send the report to higher management with Pass, failed and Skipped results, but with out Exception Summary.

Please help

Thanks & Regards
Smit Jain
9663310652

**Comment by uttesh** [comment]
Ok will look into that, if urgent i will give patch jar with that option
only for you other wise i will add in my next release.

Thanks,
Uttesh

**Comment by uttesh** [comment]
@smitjain87 Made small quick release with flag to have exception summary page in report.

pdfreport.exception.page=show/hide

All sample and web is updated with latest 2.0.6 RELEASE

**Comment by smitjain87** [comment]
Thank you so much sir.. :)

**Comment by uttesh** [comment]
Welcome smit jain, feel free to report on any issues/enhancement. ;)

cheers,
