### ISSUE TITLE
Enhancement Request: Add Lines below title

### ISSUE THREAD

**Issue by smitjain87** [uttesh/pdfngreport#7]
Hi Uttesh,

In my current project, higher management want the details like device name, os and build version and environment name, so if possible can you please provide a way through which I can enter those details below title. 

Like you provide for entering title :pdfreport.title.text 
same way three more lines for entering details below title

Please help

Thanks & Regards
Smit Jain

**Comment by sunnysachdeva** [comment]
Also the current user who is running the test.

**Comment by uttesh** [comment]
next release i will add, only build version will be from property other
will be from system, i don't manipulation of system details from property
file.

**Comment by smitjain87** [comment]
Hi,

I just need to add three lines to be added device details and other thing I will pass through Property file.you just give the way to add data after Title three lines
like: line1:..
line2:
line3: in property file

Thanks & Regards
Smit Jain
9663310652

**Comment by uttesh** [comment]
could you please elaborate line1,line2,line3  sample values.

**Comment by smitjain87** [comment]
Like you give a way to enter Title through Properties file using
pdfreport.title.text.

Similarly below title I need to enter few details like Device Name & OS version
Build name, Environment name and all these details I will enter through Property file 
so I need 3 input field below title in which I can enter data through Property files similarly like I enter title.

Thanks & Regards
Smit Jain

**Comment by uttesh** [comment]
no need to enter system details. plugin will get those details by code, only build version will be from property file, full details will be in single line.

sample screen shot
![image 27](https://cloud.githubusercontent.com/assets/2218611/8494451/c0c030aa-2182-11e5-9219-fc8f3dbde8ff.png)

**Comment by smitjain87** [comment]
Sir actully we are doing mobile Automation testing and we are not using directly selenium so we cant directly enter all the details.

We need to enter manually only through Property files, so I need three lines below title to enter data

**Comment by uttesh** [comment]
Are you using mobile simulator for testing? in that case i will provide the entry field.  i will give that as entry field from property file, but it will be single line as screen shot...i don't want to waste spaces on top bar.

**Comment by uttesh** [comment]
@smitjain87  implemented the feature and added three line for manual entering data as well. version 2.0.8 Released in maven and updated sample and official link.

@sunnysachdeva added username@hostname details.

auto generated :

![code](https://cloud.githubusercontent.com/assets/2218611/8503811/e5afd2ac-21e2-11e5-8b87-458414b4e5b1.png)

Manual Entering :
![manual](https://cloud.githubusercontent.com/assets/2218611/8503812/e927d90c-21e2-11e5-8953-5c42276975c1.png)

Properties setting : 

![properties](https://cloud.githubusercontent.com/assets/2218611/8503813/ee11b9b0-21e2-11e5-94f1-70392250b1ea.png)

**Comment by smitjain87** [comment]
Thank you sir
Regards
Smit Jain
