### ISSUE TITLE
File path error running in Mac or Linus

### ISSUE THREAD

**Issue by ghost** [uttesh/pdfngreport#8]
Hi Uttesh,

There is a configuration problem for running the plugin in Mac or Linux. For Linux, I changed the Constants.FORWARD_SLASH to “/” and in the report.xsl file, I changed the url(file:/{ReportLocation}/chart.png) to url(ReportLocation/chart.png). 

My project currently running one test case for a large number of times, using the InvocationCount in TestNG. I just wonder if possible to retrieve the count of each test case run and present it in the PDF report.

Thanks a lot for the wonderful plugin and looking forward to future releases.

**Comment by uttesh** [comment]
Thanks tim,

   i have addressed that issue in 2.8.0 version release, i will re validate the issue.

**Comment by uttesh** [comment]
Hi Tim,

 Able to reproduced the linux path issue in 2.0.8 version jar, implemented the fixed and release 2.0.9 jar which is working fine on linux/mac systems fine.

regarding invocation count i will look into that in later releases.
Thanks,
Uttesh
